export enum NETWORK {
    MAINNET = 1,
    GOERLI = 5,
    SEPOLIA_ARBITRUM_TESTNET = 421614,
    LOCALHOST = 31337,
  }

 export const CONTRACT_SEPOLIA_ARBITRUM_TESTNET = "0xeBB9868674Daa23A54e5235e950D78a733a00393";

  export const DEFAULT_NETWORK = !!process.env.NEXT_PUBLIC_CHAIN_ID
  ? Number(process.env.NEXT_PUBLIC_CHAIN_ID)
  : NETWORK.MAINNET;

export const DEFAULT_NETWORK_NAME = NETWORK[DEFAULT_NETWORK].toLowerCase();
export const CONNECTOR_KEY = "CONNECTOR";