export enum NETWORK {
    MAINNET = 1,
    GOERLI = 5,
    SEPOLIA_ARBITRUM_TESTNET = 421614,
    LOCALHOST = 31337,
  }

  const CONTRACT_SEPOLIA_ARBITRUM_TESTNET = "0x7e64463DebD272F12AD61dc991808aB209841633";

  export const DEFAULT_NETWORK = !!process.env.NEXT_PUBLIC_CHAIN_ID
  ? Number(process.env.NEXT_PUBLIC_CHAIN_ID)
  : NETWORK.MAINNET;

export const DEFAULT_NETWORK_NAME = NETWORK[DEFAULT_NETWORK].toLowerCase();
export const CONNECTOR_KEY = "CONNECTOR";